apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-hc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
        - name: cicd-app
          image: eimonwinaung/ci-cd #Image name you used to build in docker step
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  selector:
    app: cicd-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31010 #Expose 31010 as nodeport
  type: NodePort